### ISSUE TITLE
Sending to unknown sites silently fails

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.Gateway#102]
If users forget to call `.AddSite("B")` calls to `.SendToSites("A","B")` will silently just ignore it. 

We should throw on send when this is true.

**Comment by SzymonPobiega** [comment]
@Particular/keeping-the-lights-on-squad I'd say this is `critical` because of message loss possibility. The missing configuration is not likely to be detected in any test environment because gateway is likely to have different configurations between environments (i.e. production has 4 "warehouse" sites when test has only one). 

Because there's already a TF working on #98 I propose to include the fix in the scope there.
